services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nexusshop-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-nexusshop}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRES_WORK_MEM: 8MB
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexusshop-network
    mem_limit: 512m
    cpus: 0.5

  app:
    build: .
    container_name: nexusshop-api
    depends_on:
      - db
      - minio
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-nexusshop}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}

      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO:-none}
      SPRING_JPA_SHOW_SQL: ${JPA_SHOW_SQL:-true}

      COHERE_API_KEY: ${COHERE_API_KEY:-default_cohere_api_key}

      JWT_SECRET: ${JWT_SECRET:-default_secret_key}

      MINIO_URL: http://minio:9000
      MINIO_USER: ${MINIO_USER:-minioadmin}
      MINIO_PASSWORD: ${MINIO_PASSWORD:-minioadmin}
      MINIO_BUCKET: ratings

      JAVA_TOOL_OPTIONS: >-
        -Xms128m
        -Xmx512m
        -XX:+UseSerialGC
        -XX:MaxRAMPercentage=75
        -Dfile.encoding=UTF-8

    restart: always
    networks:
      - nexusshop-network

  minio:
    image: minio/minio
    container_name: nexusshop-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console web
    volumes:
      - minio_data:/data
    networks:
      - nexusshop-network
  
volumes:
  postgres_data:
  minio_data:

networks:
  nexusshop-network:
    driver: bridge