INSERT INTO product (name, description, price, stock, category) VALUES
('Smartphone X', 'High-end smartphone with OLED display', 2999.99, 50, 'ELETRONICOS'),
('Laptop Pro', 'Powerful laptop for professionals', 5999.90, 20, 'ELETRONICOS'),
('Wireless Headphones', 'Noise-cancelling over-ear headphones', 899.99, 35, 'ELETRONICOS'),
('Office Chair', 'Ergonomic chair for office use', 649.50, 15, 'MOVEIS'),
('Gaming Mouse', 'High precision RGB gaming mouse', 199.90, 80, 'ELETRONICOS'),
('Mechanical Keyboard', 'RGB mechanical keyboard with blue switches', 349.90, 60, 'ELETRONICOS'),
('Running Shoes', 'Comfortable running shoes', 249.99, 40, 'ROUPAS'),
('Backpack', 'Durable backpack for travel and work', 159.90, 70, 'ACESSORIOS'),
('Coffee Maker', 'Automatic drip coffee maker', 299.00, 25, 'ELETRODOMESTICOS'),
('Desk Lamp', 'LED desk lamp with adjustable brightness', 89.90, 55, 'MOVEIS'),
('Tablet Plus', '10-inch tablet with high resolution screen', 1899.99, 30, 'ELETRONICOS'),
('Smartwatch Fit', 'Fitness smartwatch with heart rate monitor', 799.90, 45, 'ELETRONICOS'),
('Bluetooth Speaker', 'Portable speaker with deep bass', 299.99, 65, 'ELETRONICOS'),
('4K Monitor', '27-inch 4K UHD monitor', 1799.00, 18, 'ELETRONICOS'),
('USB-C Hub', 'Multiport adapter with HDMI and USB 3.0', 149.90, 90, 'ACESSORIOS'),
('External SSD 1TB', 'High-speed portable SSD storage', 699.90, 25, 'ELETRONICOS'),
('Office Desk', 'Spacious wooden office desk', 899.00, 12, 'MOVEIS'),
('Bookshelf', '5-tier wooden bookshelf', 499.90, 20, 'MOVEIS'),
('Floor Lamp', 'Modern floor lamp with warm lighting', 229.90, 28, 'MOVEIS'),
('Air Fryer', 'Oil-free air fryer with digital panel', 399.99, 33, 'ELETRODOMESTICOS'),
('Blender Pro', 'High-power blender with glass jar', 249.90, 40, 'ELETRODOMESTICOS'),
('Vacuum Cleaner', 'Bagless vacuum cleaner with strong suction', 599.00, 22, 'ELETRODOMESTICOS'),
('T-shirt Basic', 'Cotton basic t-shirt', 49.90, 100, 'ROUPAS'),
('Jeans Slim Fit', 'Comfortable slim fit jeans', 129.90, 55, 'ROUPAS'),
('Jacket Winter', 'Warm winter jacket', 299.90, 35, 'ROUPAS'),
('Sneakers Casual', 'Stylish casual sneakers', 199.90, 60, 'ROUPAS'),
('Sunglasses', 'UV protection sunglasses', 89.90, 75, 'ACESSORIOS'),
('Wallet Leather', 'Genuine leather wallet', 119.90, 50, 'ACESSORIOS'),
('Travel Suitcase', 'Medium size durable suitcase', 349.90, 27, 'ACESSORIOS'),
('Electric Kettle', 'Fast boiling electric kettle', 159.90, 38, 'ELETRODOMESTICOS'),
('Gaming Chair', 'Ergonomic gaming chair with lumbar support', 1299.90, 14, 'MOVEIS'),
('Router Wi-Fi 6', 'High-speed dual band Wi-Fi 6 router', 499.90, 32, 'ELETRONICOS'),
('Webcam HD', '1080p webcam with built-in microphone', 219.90, 46, 'ELETRONICOS'),
('Microphone USB', 'Studio quality USB microphone', 349.90, 29, 'ELETRONICOS'),
('Power Bank 20000mAh', 'Portable fast-charging power bank', 179.90, 70, 'ACESSORIOS'),
('Smart TV 50"', '50-inch 4K Smart TV with HDR', 2799.00, 10, 'ELETRONICOS'),
('Soundbar', 'Home theater soundbar system', 899.90, 21, 'ELETRONICOS'),
('Hair Dryer', 'Compact hair dryer with multiple settings', 129.90, 58, 'ELETRODOMESTICOS'),
('Electric Iron', 'Steam electric iron', 149.90, 44, 'ELETRODOMESTICOS'),
('Mixer', 'Kitchen mixer with multiple speeds', 299.90, 26, 'ELETRODOMESTICOS'),
('Dress Casual', 'Light casual dress for everyday wear', 139.90, 48, 'ROUPAS'),
('Shorts Sport', 'Breathable sports shorts', 79.90, 67, 'ROUPAS'),
('Cap Adjustable', 'Adjustable cap with curved brim', 59.90, 85, 'ACESSORIOS'),
('Notebook 15"', '15-inch notebook for daily tasks', 3499.00, 16, 'ELETRONICOS'),
('Mouse Pad XL', 'Extended mouse pad for desk setup', 89.90, 73, 'ACESSORIOS'),
('LED Strip Lights', 'RGB LED strip with remote control', 119.90, 52, 'ACESSORIOS'),
('Bedside Table', 'Compact bedside table with drawer', 279.90, 19, 'MOVEIS'),
('Wardrobe 3 Doors', 'Spacious wardrobe with 3 doors', 1599.00, 8, 'MOVEIS'),
('Dish Rack', 'Stainless steel dish drying rack', 99.90, 61, 'ELETRODOMESTICOS'),
('Toaster', '2-slice toaster with browning control', 139.90, 37, 'ELETRODOMESTICOS')
 WHERE NOT EXISTS (SELECT 1 FROM product);